name = "withered-fog-bd95"
main = "src/index.js"
compatibility_date = "2023-03-08"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[[r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'test1'

[durable_objects]
bindings = [
  { name = "DURABLE_OBJECT_NAME", class_name = "R2Reader" } # Binding to our DurableObjectExample class
]

