export default {
	async fetch(request, env) {
		const url = new URL(request.url)

		if (url.pathname === "/admin") {
			return new Response("Admin page");
		}

		const html = `<!DOCTYPE html>
		<body>
		  <h1>Hello World 2</h1>
		  <p>This markup was generated by a Cloudflare Worker.</p>
		</body>`;

		await env.MY_BUCKET.put(`test_key ${Date.now()}`, { "object_key": "object_value"});

		return new Response(html, {
			headers: {
				'content-type': 'text/html;charset=UTF-8',
			},
		});
	},
};
